context:
  version: "2.9.2"

package:
  name: tensorizer
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/t/tensorizer/tensorizer-${{ version }}.tar.gz
    sha256: 973a69e9247ee393625850ef9152cd65acd163a60db39ca6edad376f503cffe5

build:
  noarch: python
  number: 0
  script: ${{ PYTHON }} -m pip install .

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - pytorch >=1.9.0
    - numpy >=1.19.5
    - protobuf >=3.19.5
    - psutil >=5.9.4
    - boto3 >=1.26.0
    - redis-py >=4.5.5
    - hiredis >=2.2.0
    - libnacl-python-bindings >=2.1.0

tests:
  - python:
      imports:
        - tensorizer
      pip_check: true
      python_version: ${{ python_min }}.*
  - files:
      source:
        - tests/
    requirements:
      run:
        - pytest
        - pytest-rerunfailures
        - transformers >=4.27.1
        - moto >=4.1.4,<5.0.0
        - redis-py >=5.0.0
        - if: not win
          then:
            - redis-server
        - boto3
    script:
    # Redis tests are flaky, sometimes failing with:
    #     redis.exceptions.ConnectionError: Error 111 connecting to localhost:6381.
    #     Connection refused.
    # I suspect that there's not enough startup time, so we retry a few times.
      - if: linux
        then:
          - pytest tests -vvv --reruns 2

about:
  homepage: https://github.com/coreweave/tensorizer
  repository: https://github.com/coreweave/tensorizer
  summary: A tool for fast PyTorch module, model, and tensor serialization + deserialization.
  description: Module, Model, and Tensor Serialization/Deserialization
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
